### ISSUE TITLE
WORKSHOP: StavangerNodeschool #2 - Functional Javascript

### ISSUE THREAD

**Issue by asbjornenge** [nodeschool/stavanger#5]
Started en tråd her for diskusjon og spm. før, under og etter workshop'en nå på torsdag :rocket: 
Så får jeg samtidig testet om jeg kan sende notification til alle medlemmene via github @nodeschool/stavanger :grin: :see_no_evil:

**Comment by VirtueMe** [comment]
Genialt!

**Comment by asbjornenge** [comment]
:tada: 

PS! Jeg nevnte det på IRC, men jeg kommer litt i siste liten på torsdag. Skal på fotball trening med eldstemann 5-6. Så ingen vits å møte opp halv 7 og stå å fryse på utsiden :snowman: :+1:
