### ISSUE TITLE
International Day Event

### ISSUE THREAD

**Issue by martinheidegger** [nodeschool/stavanger#6]
Hello guys, @asbjornenge  signed you up for the international day but it seems you havn't come around to setup an event site yet! See: nodeschool/international-day#22

**Comment by asbjornenge** [comment]
@martinheidegger yup, but it turns out I'll be in Oslo for the one-shot-conf on the 23rd. I haven't been able to get anyone else to take charge...

**Comment by martinheidegger** [comment]
Do you think it is going to happen or should it be unenrolled?

**Comment by asbjornenge** [comment]
@martinheidegger I think we need to be unenrolled. I've been reaching out, but nobody has stepped up. I'll make sure to improve planning for next year.

**Comment by martinheidegger** [comment]
I understand, no problem!
